mindmap
  root((L'atur))
    Que es?
        Conceptes: població en edat de treballar, activa, inactiva i ocupada
    Com el mesurem?
        Taxes: atur i activitat
    Com s'explica? les teories
        Teoria neoclàssica: equilibri al mercat de treball -> Solució: rebaixar salaris
        Teoria marxista: exèrcit de reserva
        Teoria keynesiana: demanda derivada necessitats productives
        Teoria capital humà: nivell formació individual.
